### ISSUE TITLE
IntelligentEnergistics breaks step up ability in Botiana

### ISSUE THREAD

**Issue by 55chevypickup** [thatsIch/IntelliE#15]
When IntelligentEnergistics and botiana are installed it breaks the step up ability of the Soujourner's sash. It also stop the step up of the horse in morph.

**Comment by thatsIch** [comment]
What would be a desired effect? I have never played either of both mods, so I am not aware how you define "breaks"

**Comment by wasweb** [comment]
Soujourner's sash increases player.stepHeight like IntelliE's horseshoes, but IntelliE's registration logic sets the stepHeight to 0.5F even when the Soujourner's sash or something else would override it. It's even breaks one of the Tinkers' armor functionality. Here is the TiC logic for changing stepheight: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/armor/ArmorAbilities.java#L71-L82

**Comment by thatsIch** [comment]
ok, this seems like an easy fix, I think. I will take a look into that.

**Comment by thatsIch** [comment]
New version should fix this, thanks for reporting
