### ISSUE TITLE
Wrong ingame info.

### ISSUE THREAD

**Issue by NJM1564** [thatsIch/IntelliE#17]
Info says AappliedAerodynamics.
![2015-03-09_20 17 59](https://cloud.githubusercontent.com/assets/4961158/6567177/71224f2c-c699-11e4-9cc7-7d4d3c48fa4e.png)

**Comment by thatsIch** [comment]
This is correct, its a sub mod in IntelliE

IntelliE consists of:

* Applied Aerodynamics (free build tools) WIP
* Applied Agricultures (farming automation) N/A
* Applied Intelligence (process optimization) N/A
