### ISSUE TITLE
Feature Suggestion: Jetpack?

### ISSUE THREAD

**Issue by Badcholo** [thatsIch/IntelliE#19]
Is There a way to achieve flight?

**Comment by Badcholo** [comment]
I ment a better more jetpack feel. Also remove fall damage, but i see it takes reduced fall damage already. Creative mod flying seems to sometimes not work. Does it have a cooldown?

**Comment by Badcholo** [comment]
i would love to see this turn into a Power Armor from voltz Armor/play style. I don't think they are updating their mod anymore. I'm still trying to make a voltz 1.7.10 modpack/server.

**Comment by thatsIch** [comment]
No, it is meant as an improved creative flight without the stupid jaggering which is really annoying when building and engineering.

What you mean with reduced fall damage, there is

     workbench=aero:horseshoes ae2:ItemMaterial.EngProcessor 1 aero:absorptionratio -> aero:horseshoes

I have no clue what the Power Armor is, I do not play Minecraft.

**Comment by Badcholo** [comment]
Hover mode Can be used to keep you in 1 place and not move you up and down. Shift moves you down slowly and space moves you up slowly. Takes constant energy. It's like creative mode flying but a slight slower going up and down. Also hover mode is not removed upon landing. Not being in hover mode can move you up much faster and you fall like if you had no jetpack on. Removing fall damage on a suit that flies is best, such as a shock absorber upgrade. Hover mode is for building while jetpack mode is for getting out of water, lava or any kind of danger quickly, such as pvp. Also can you make it so that it will put you out of fire when you come out of lava. It's just annoying to run around with fire on even thou you take no damage. 
http://www.technicpack.net/modpack/mojangsters.583708
you dont play minecraft?

**Comment by thatsIch** [comment]
**Speed**
The omnidirectional speed is intentional. If you want that behaviour, your are better of using those jetpacks. I want to keep it simple and save, too much behavior is not needed in a 300 mod environment, where each and every key has already 3 different effects.

**Fall Damage**
There is already damage absorption in the shoes, not sure what else you expect.

**Fire**
This is something I could consider. Need to see, how much time I get for IE (since working on AE2 rv3 has higher priority)

**Playing**
No, I do not.

**Comment by Badcholo** [comment]
Well, i had high hopes for this mod in Survival. Flying in creative mode is just horrible in survival, plus it doesn't work all the time. right clicking and the block being auto mined and placed in your inventory feels like creative mode playing. It just doesn't feel like survival. The armor protects you from all damage, lava, fire and the power lasts for a very long time, but take a little jump off a little hill and hearts are lost, just seems dumb. Good luck with the mod, but i really don't know what your target player is or why make the mod at all. Most creative mode players don't need armor or tools. Survival is about a min. amount of realism. Good luck but yeah, i guess i'll stick with Simply Jetpacks.

**Comment by thatsIch** [comment]
try reading http://minecraft.curseforge.com/mc-mods/222848-intelligent-energistics
