### ISSUE TITLE
AppliedAerodynamics armor suit wont charge in AE2 charger

### ISSUE THREAD

**Issue by vendris-DeVcoFTB** [thatsIch/IntelliE#20]
Hello,

We are currently running appliedenergistics2 rv2 stable 10 
and IntelligentEnergistics-1.7.10-2.1.4.554-universal.

The armor suit that comes with Intelligent Energistics is supposed to be charged with the AE2 charger, but inserting the armor in the charger has no effect. 

-vendris

**Comment by thatsIch** [comment]
Need to check later on, dont have much time atm.

**Comment by mydayyyy** [comment]
I have the Bug too. Very expansive Armor but dont Charge. Is there any Hotfix come?

**Comment by thatsIch** [comment]
I will look into this now. Hope I will find the issue fast.

**Comment by thatsIch** [comment]
I just tried it and I can charge it.
Did you insert an energy cell to increase the maximum available energy possible?

**Comment by thatsIch** [comment]
Closing this issue since I cant reproduce this
