### ISSUE TITLE
Freerunner Discharging 

### ISSUE THREAD

**Issue by blackrulz** [thatsIch/IntelliE#24]
Hello

I don’t know if it’s intended or not, but strange anyways.
Only the Freerunner is discharging when I’m not using it, if the set is equipped, and not used the charge is constant on the helmet, chestnut, and  shoes.
Standing still with only a basic cell installed can eat up the charge in minutes.

It is a pain as with dense cell+90 calc processors installed the drain is still notable :(

**Comment by blackrulz** [comment]
For an extra point, the fly activation is sometimes hectic, the double tapping space have to be too fast as i feel, most of the times it is hard to enable or disable it

**Comment by thatsIch** [comment]
1. I try to look into it when I have time for that
2. the double tapping is the same as the minecraft vanilla creative. I guess, I could make that configurable?
