### ISSUE TITLE
Crafting Issue/Cheaty problem with Skystone Ingot in a Inscriber

### ISSUE THREAD

**Issue by MJRLegends** [thatsIch/IntelliE#25]
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/451 as it was posted on my mod packs issue tracker

**Comment by thatsIch** [comment]
I will take a look at it next week

**Comment by MJRLegends** [comment]
Sweet

**Comment by thatsIch** [comment]
Is this one of your users? https://github.com/thatsIch/IntelliE/issues/26

If yes, please tell your users to refrain to such spam (I already deleted like 20 **duplicate** messages). This is not helping at all.

**Comment by MJRLegends** [comment]
Yeah hes been doing it to me too, hes a bit of a idiot sorry

**Comment by MJRLegends** [comment]
@thatslch please can you remove my messages from #26 as i would rather not be associated with him

**Comment by MJRLegends** [comment]
@thatsIch Dont mean to be pushy but have you managed to look in to the issue. Dont worry if you haven't i'm just chasing my posted issues that i have submitted

**Comment by thatsIch** [comment]
not yet

**Comment by thatsIch** [comment]
The fix will be contained in the latest version on curseforge. Thanks for reporting and staying patient o/

**Comment by MJRLegends** [comment]
Sweet thanks
