### ISSUE TITLE
frezzing game error 

### ISSUE THREAD

**Issue by optimze** [thatsIch/IntelliE#26]
first of it bc quarrys that crash me
explain how to copy this log?

**Comment by optimze** [comment]
http://paste.feed-the-beast.com/view/cbdbcc90

**Comment by optimze** [comment]
http://paste.feed-the-beast.com/view/cbdbcc90

**Comment by optimze** [comment]
http://paste.feed-the-beast.com/view/cbdbcc90

**Comment by optimze** [comment]
please help i cant play till helped

**Comment by optimze** [comment]
11 hours later

**Comment by optimze** [comment]
its when a machine shows something like an effect ender quarry also

**Comment by optimze** [comment]
..,,
.

**Comment by optimze** [comment]
24 hours later

**Comment by optimze** [comment]
SOMEONE!

**Comment by thatsIch** [comment]
Why you writing me? This crash has nothing to do with IntelliE besides this it being installed.

Line 555*ff are just showing some random chunk error.

And spamming the issue tracker of some Mod Author will nethier increase the response time nor the willingness to help.

Check if you have the correct client version of your server. After that disable mods which might cause problems on both client and server.

**Comment by MJRLegends** [comment]
Optimze stop being a idiot and spamming everyone or you will find your self banned from the places you spam

**Comment by optimze** [comment]
why does bc crash me only on that server in single player im fine?

**Comment by MJRLegends** [comment]
@optimze i dont know, stop spamming everyone and being a dick about it as its pissing people off....

**Comment by optimze** [comment]
ok then the digi does it to when i click on visial effect.

**Comment by MJRLegends** [comment]
@optimze im not helping you now as you have annoyed me

**Comment by optimze** [comment]
You never helped me get the write logs that all i chould get..

**Comment by MJRLegends** [comment]
@optimze your not getting my server logs and im not helping you, im not wasting my time on a spammer that is acting like a 5 year old

**Comment by optimze** [comment]
thanks
its pissing when staff help but they just littel info on what to do

**Comment by MJRLegends** [comment]
@optimze Bye

**Comment by optimze** [comment]
so your keeping be broke...

**Comment by thatsIch** [comment]
This is not the correct place to disguss such matter. Please deal with it in a PM
