### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MPeti1** [thatsIch/IntelliE#35]
If I add this mod the the mods folder, the game will crash on startup. Here are the logs:
[latest.log](https://github.com/thatsIch/IntelliE/files/1958175/latest.log)
[2018-04-28-7.log](https://github.com/thatsIch/IntelliE/files/1958176/2018-04-28-7.log)

**Comment by thatsIch** [comment]
The Log doesn't state anything for me to debug.

**Comment by MPeti1** [comment]
The problem somehow solved itself. I don't really remember but i think i removed some mods because they caused other problems, and now its working
